pages:
  - name: Home
    columns:
      - size: full
        widgets:
          - type: clock
            hour-format: 24h
            timezones:
              - timezone: America/New_York
                label: New York
              - timezone: UTC
                label: UTC
            title: kk
          - type: bookmarks
            groups:
              - title: General
                links:
                  - title: GitHub
                    url: https://github.com
                  - title: Google
                    url: https://google.com
          - type: calendar
            first-day-of-week: monday
  - name: News
    slug: news
    columns:
      - size: small
        widgets:
          - type: hacker-news
            limit: 10
            collapse-after: 5
      - size: full
        widgets:
          - type: rss
            title: Tech News
            style: vertical-list
            limit: 15
            feeds:
              - url: https://hnrss.org/frontpage
                title: Hacker News
  - name: Page 3
    columns:
      - size: full
        widgets:
          - type: hacker-news
            title: Hacker Ne
            limit: 15
            collapse-after: 5
            sort-by: top
theme:
  background-color: 240 14 15
  primary-color: 220 80 50
  contrast-multiplier: 1.1
